#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["SMS_Service.Console/SMS_Service.Console.csproj", "SMS_Service.Console/"]
COPY ["SMS_Service.Common/SMS_Service.Common.csproj", "SMS_Service.Common/"]
RUN dotnet restore "SMS_Service.Console/SMS_Service.Console.csproj"
COPY . .
WORKDIR "/src/SMS_Service.Console"
RUN dotnet build "SMS_Service.Console.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SMS_Service.Console.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SMS_Service.Console.dll"]