version: '3.8'

services:
  db:
    container_name: fdx-db
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_USER=fdxuser
      - POSTGRES_PASSWORD=Aa123456
      - POSTGRES_DB=fdxdb
    ports:
      - '5432:5432'
  broker:
    container_name: broker
    image: masstransit/rabbitmq
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
  api:
    container_name: api
    restart: always
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
       - '5000:80'
    depends_on:
      - db
      - broker
    command: ["dotnet", "ef", "database update"]
  console-app:
    container_name: console-app
    restart: always
    build:
      context: './server'
      dockerfile: Dockerfile-console
    depends_on:
      - broker